project/apps/catalogo/urls.py
from django.urls import path
from .views import *

app_name = "catalogo"

urlpatterns = [
    path("", index, name="index"),
    path("categoria/list/", CategoriaList.as_view(), name="categoria_list"),
    path("categoria/form/", CategoriaCreate.as_view(), name="categoria_form"),
    path("categoria/update/<int:pk>/",
         CategoriaUpdate.as_view(), name="categoria_update"),
    path("categoria/delete/<int:pk>/",
         CategoriaDelete.as_view(), name="categoria_delete"),
    path("producto/list/", ProductoList.as_view(), name="producto_list"),
    path("producto/form/", ProductoCreate.as_view(), name="producto_form"),
    path("producto/update/<int:pk>/",
         ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>/", ProductoDelete.as_view(),
         name="producto_confirm_delete"),
    path("producto/detail/<int:pk>/",
         ProductoDetail.as_view(), name="producto_detail"),
    path("venta/list/", VentaList.as_view(), name="venta_list"),
    path("venta/form/", VentaCreate.as_view(), name="venta_form"),
    path("venta/update/<int:pk>/", VentaUpdate.as_view(), name="venta_update"),
    path("venta/delete/<int:pk>/", VentaDelete.as_view(),
         name="venta_confirm_delete"),
]

project/apps/cliente/urls.py
from django.urls import path
from .views import *

app_name = "cliente"

urlpatterns = [
    #    path("", index, name="index"),
    path("cliente/list/", ClienteList.as_view(), name="cliente_list"),
    path("cliente/form/", ClienteCreate.as_view(), name="cliente_form"),
    path("cliente/update/<int:pk>/", ClienteUpdate.as_view(), name="cliente_update"),
    path("cliente/delete/<int:pk>/", ClienteDelete.as_view(),
         name="cliente_confirm_delete"),
    path("cliente/detail/<int:pk>/", ClienteDetail.as_view(), name="cliente_detail"),
]

project/apps/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact_view, name="contact_form"),
    path("contacto_exitoso/", contacto_exitoso, name="contacto_exitoso"),
    path("about/", about, name="about"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("catalogo/", include("catalogo.urls")),

]

project/apps/catalogo/models.py
from django.db import models
from django.utils import timezone
from cliente.models import Cliente


class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre}"


class Producto(models.Model):
    nombre = models.CharField(max_length=150)
    categoria = models.ForeignKey(
        Categoria, null=True, blank=True, on_delete=models.SET_NULL)
    precio = models.FloatField()
    fecha_creacion = models.DateField(
        default=timezone.now, editable=False, verbose_name="fecha de creación")
    descripcion = models.TextField(
        null=True, blank=True, verbose_name="descripción")

    def __str__(self):
        return f"{self.nombre}, {self.precio}"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"


class Venta(models.Model):
    operacion = models.AutoField(primary_key=True)
    articulo = models.ForeignKey(
        Producto, null=True, blank=True, on_delete=models.SET_NULL)
    cliente = models.ForeignKey(
        Cliente, null=True, blank=True, on_delete=models.SET_NULL)
    cantidad = models.FloatField(verbose_name="cantidad")
    precio_unitario = models.FloatField(
        default=0, editable=False, verbose_name="precio unitario")
    precio_neto = models.FloatField(
        default=0, editable=False, verbose_name="precio neto")
    fecha_operacion = models.DateField(
        default=timezone.now, editable=False, verbose_name="fecha de operación")

    def save(self,  *args, **kwargs):
        self.precio_unitario = self.articulo.precio
        self.precio_neto = float(self.precio_unitario) * float(self.cantidad)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.operacion}, {self.fecha_operacion}, {self.articulo}, {self.cantidad}, {self.precio_unitario}, {self.precio_neto}"

    class Meta:
        verbose_name = "venta"
        verbose_name_plural = "ventas"

project/apps/catalogo/forms.py
from django import forms

from . import models


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = models.Categoria
        fields = "__all__"

class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        
        
class VentaForm(forms.ModelForm):
    class Meta:
        model = models.Venta
        fields = "__all__"

project/apps/catalogo/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)


def index(request):
    return render(request, "catalogo/index.html")


class CategoriaList(ListView):
    model = Categoria
    template_name = 'catalogo/categoria_list.html'

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = Categoria.objects.filter(nombre__icontains=consulta)
        else:
            object_list = Categoria.objects.all()
        return object_list


class CategoriaCreate(LoginRequiredMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy("catalogo:categoria_list")


class CategoriaUpdate(LoginRequiredMixin, UpdateView):
    model = Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy("catalogo:categoria_list")


class CategoriaDelete(LoginRequiredMixin, DeleteView):
    model = Categoria
    success_url = reverse_lazy("catalogo:categoria_list")


class ProductoList(ListView):
    model = Producto
    template_name = 'catalogo/producto_list.html'

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = Producto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = Producto.objects.all()
        return object_list


class ProductoCreate(LoginRequiredMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("catalogo:producto_list")


class ProductoUpdate(LoginRequiredMixin, UpdateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("catalogo:producto_list")


class ProductoDelete(LoginRequiredMixin, DeleteView):
    model = Producto
    success_url = reverse_lazy("catalogo:producto_list")


class ProductoDetail(DetailView):
    model = Producto


class VentaList(ListView):
    model = Venta
    template_name = 'catalogo/venta_list.html'

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = Venta.objects.filter(operacion__icontains=consulta)
        else:
            object_list = Venta.objects.all()
        return object_list


class VentaCreate(LoginRequiredMixin, CreateView):
    model = Venta
    form_class = VentaForm
    success_url = reverse_lazy("catalogo:venta_list")


class VentaUpdate(LoginRequiredMixin, UpdateView):
    model = Venta
    form_class = VentaForm
    success_url = reverse_lazy("catalogo:venta_list")


class VentaDelete(LoginRequiredMixin, DeleteView):
    model = Venta
    success_url = reverse_lazy("catalogo:venta_list")

project/apps/catalogo/templates/catalogo/categoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block content_title %}
Eliminar Categoria
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Confirma que quiere eliminar {{ object.nombre }} del listado de Categorias?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'catalogo:categoria_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/categoria_form.html
{% extends 'core/base.html' %}

{% block content_title %}
Crear Categoria
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Guardar</button>
    <a href="{% url 'catalogo:categoria_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/categoria_list.html
{% extends 'core/base.html' %}

{% block content_title %}
Categorías de artículos
{% endblock content_title %}

{% block content %}
<div class="container">
    <div class="mb-4">
        <form method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar categoria">
        </form>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Categorias</th>
            </tr>
        </thead>
        <tbody>
            {% if user.is_staff %}
            <a href="{% url 'catalogo:categoria_form' %}" class="btn btn-danger">Agregar categoria</a>
            {% endif %}
            {% for categoria in object_list %}
            <tr>
                <td>{{ categoria.nombre }}</td>
                <td>
                    {% if user.is_staff %}

                    <a href=" {% url 'catalogo:categoria_update' categoria.id %}" class="btn btn-danger"><i
                            class="fas fa-pencil-alt"></i> Editar</a>
                    <a href="{% url 'catalogo:categoria_delete' categoria.id %}" class="btn btn-danger "><i
                            class="fas fa-trash-alt"></i>Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td class="text-center">No hay categorías disponibles.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

project/apps/catalogo/templates/catalogo/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<!-- Content Row-->
<div class="row gx-4 gx-lg-5">
    {% include 'catalogo/tarjetas.html' %}

</div>
{% endblock content %}

project/apps/catalogo/templates/catalogo/producto_confirm_delete.html
{% extends 'core/base.html' %}

{% block content_title %}
Eliminar Artículo
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Confirma que quiere eliminar {{ object.nombre }} del catálogo?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'catalogo:producto_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/producto_detail.html
{% extends 'core/base.html' %}

{% block content_title %}
Detalle de Artículo
{% endblock content_title %}

{% block content %}
<div class="container">

    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">{{ object.nombre }}</h5>
            <p class="card-text">Precio: ${{ object.precio }}</p>
            <h6 class="card-title">Descripción:</h6>
            <p class="card-text">{{ object.descripcion }}</p>
        </div>
    </div>

    <div class="mt-4">
        <a href="{% url 'catalogo:producto_list' %}" class="btn btn-danger">Volver a la Lista</a>
        {% if user.is_staff %}
        <a href="{% url 'catalogo:producto_update' object.id %}" class="btn btn-danger">Editar</a>
        <a href="{% url 'catalogo:producto_confirm_delete' object.id %}" class="btn btn-danger">Eliminar</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

project/apps/catalogo/templates/catalogo/producto_form.html
{% extends 'core/base.html' %}

{% block content_title %}
Crear Artículo
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Guardar</button>
    <a href="{% url 'catalogo:producto_list' %}" class="btn btn-danger">Cancelar</a>
</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/producto_list.html
{% extends 'core/base.html' %}


{% block content_title %}
Catálogo de productos
{% endblock content_title %}

{% block content %}
<div class="container">
    <div class="mb-4">
        <form method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar artículo">
        </form>
    </div>
    {% if user.is_staff %}
    <a href="{% url 'catalogo:producto_form' %}" class="btn btn-danger">Agregar artículo</a>
    <a href="{% url 'catalogo:categoria_form' %}" class="btn btn-danger">Crear categoría</a>
    {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Artículos</th>
                <th>Precio</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            {% for articulo in object_list %}
            <tr>
                <td>{{ articulo.nombre }}</td>
                <td>{{ articulo.precio }}</td>
                <td>{{ articulo.categoria }}</td>
                <td>
                    <a href="{% url 'catalogo:producto_detail' articulo.id %}" class="btn btn-danger">
                        <i class="fas fa-star"></i> Detalle</a>
                    {% if user.is_staff %}
                    <a href=" {% url 'catalogo:producto_update' articulo.id %}" class="btn btn-danger"><i
                            class="fas fa-pencil-alt"></i> Editar</a>
                    <a href="{% url 'catalogo:producto_confirm_delete' articulo.id %}" class="btn btn-danger "><i
                            class="fas fa-trash-alt"></i>Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td class="text-center">No hay artículos disponibles.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

project/apps/catalogo/templates/catalogo/tarjetas.html
{% load static %}

<div class="col-md-6 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title text-center">Catálogo</h2>
        </div>
    </div>
    <div class="card-footer d-grid"><a href="producto/list" class="btn btn-danger btn-sm">Ver</a>
    </div>
</div>


{% if user.is_authenticated %}
<div class="col-md-6 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title text-center">Ventas</h2>
        </div>
    </div>
    <div class="card-footer d-grid"><a href="venta/list" class="btn btn-danger btn-sm">Ver</a>
    </div>
</div>

<div class="col-md-6 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title text-center">Clientes</h2>
        </div>
    </div>
    <div class="card-footer d-grid"><a href="{% url 'cliente:cliente_list' %}" class="btn btn-danger btn-sm">Ver</a>
    </div>
</div>

<div class="col-md-6 mb-5">
    <div class="card h-90">
        <div class="card-body">
            <h2 class="card-title text-center">Gestionar categorias</h2>
        </div>
    </div>
    <div class="card-footer d-grid"><a href="categoria/list" class="btn btn-danger btn-sm">Ver</a>
    </div>
</div>
{% endif %}

project/apps/catalogo/templates/catalogo/venta_confirm_delete.html
{% extends 'core/base.html' %}

{% block content_title %}
Eliminar registro de venta
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Confirma que quiere eliminar {{ object.operacion }}?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'catalogo:venta_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/venta_form.html
{% extends 'core/base.html' %}

{% block content_title %}
Registro de venta
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Guardar</button>
    <a href="{% url 'catalogo:venta_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/catalogo/templates/catalogo/venta_list.html
{% extends 'core/base.html' %}


{% block content_title %}
Ventas realizadas
{% endblock content_title %}

{% block content %}
<div class="container">
    <div class="mb-4">
        <form method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar transacción">
        </form>
    </div>

    <a {% if user.is_authenticated %} href="{% url 'catalogo:venta_form' %}" {% else %} href="{% url 'core:login' %}"
        {%endif %} class="btn btn-danger">Ingresar una venta</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#Operación</th>
                <th>#Fecha</th>
                <th>Articulo</th>
                <th>Cliente</th>
                <th>Cantidad</th>
                <th>Precio unitario</th>
                <th>Precio total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.operacion }}</td>
                <td>{{ item.fecha_operacion }}</td>
                <td>{{ item.articulo.nombre }}</td>
                <td>{{ item.cliente }}</td>
                <td>{{ item.cantidad }}</td>
                <td>{{ item.precio_unitario }}</td>
                <td>{{ item.precio_neto }}</td>
                <td>
                    <a href=" {% url 'catalogo:venta_update' item.pk %}" class="btn btn-danger"><i
                            class="fas fa-pencil-alt"></i> Editar</a>
                    {% if user.is_staff %}
                    <a href="{% url 'catalogo:venta_confirm_delete' item.pk %}" class="btn btn-danger"><i
                            class="fas fa-trash-alt"></i>Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td class="text-center">No hay información disponible.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}