project/apps/cliente/urls.py
from django.urls import path
from .views import *

app_name = "cliente"

urlpatterns = [
    #    path("", index, name="index"),
    path("cliente/list/", ClienteList.as_view(), name="cliente_list"),
    path("cliente/form/", ClienteCreate.as_view(), name="cliente_form"),
    path("cliente/update/<int:pk>/", ClienteUpdate.as_view(), name="cliente_update"),
    path("cliente/delete/<int:pk>/", ClienteDelete.as_view(),
         name="cliente_confirm_delete"),
    path("cliente/detail/<int:pk>/", ClienteDetail.as_view(), name="cliente_detail"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("catalogo/", include("catalogo.urls")),

]

project/apps/cliente/models.py
from django.db import models
from datetime import *


class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    email = models.EmailField()
    fecha_alta = models.DateField()

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

    class Meta:
        verbose_name = "cliente"
        verbose_name_plural = "clientes"

project/apps/cliente/forms.py
from django import forms

from . import models


class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = "__all__"

project/apps/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)


class ClienteList(ListView):
    model = Cliente
    template_name = 'cliente/cliente_list.html'

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = Cliente.objects.filter(nombre__icontains=consulta)
        else:
            object_list = Cliente.objects.all()
        return object_list


class ClienteCreate(LoginRequiredMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    success_url = reverse_lazy("cliente:cliente_list")


class ClienteUpdate(LoginRequiredMixin, UpdateView):
    model = Cliente
    form_class = ClienteForm
    success_url = reverse_lazy("cliente:cliente_list")


class ClienteDelete(LoginRequiredMixin, DeleteView):
    model = Cliente
    success_url = reverse_lazy("cliente:cliente_list")


class ClienteDetail(DetailView):
    model = Cliente

project/apps/cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'core/base.html' %}

{% block content_title %}
Eliminar Cliente
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Confirma que quiere eliminar al cliente {{ object.nombre }} {{object.apellido}}?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'cliente:cliente_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/cliente/templates/cliente/cliente_detail.html
{% extends 'core/base.html' %}

{% block content_title %}
Información del cliente
{% endblock content_title %}

{% block content %}
<div class="container">

    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">Cliente {{object.nombre}} {{object.apellido}}</h5>
            <p class="card-text">Email: {{ object.email }}</p>
            <p class="card-text">Fecha de nacimiento: {{ object.fecha_nacimiento }}</p>
            <p class="card-text">Fecha de alta:{{ object.fecha_alta }}</p>
        </div>
    </div>

    <div class="mt-4">
        <a href="{% url 'cliente:cliente_list' %}" class="btn btn-danger">Volver a la Lista</a>
        <a href="{% url 'cliente:cliente_update' object.id %}" class="btn btn-danger">Editar</a>
        {% if user.is_staff %}
        <a href="{% url 'cliente:cliente_confirm_delete' object.id %}" class="btn btn-danger">Eliminar</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

project/apps/cliente/templates/cliente/cliente_form.html
{% extends 'core/base.html' %}

{% block content_title %}
Alta de cliente
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Guardar</button>
    <a href="{% url 'cliente:cliente_list' %}" class="btn btn-danger">Cancelar</a>

</form>
{% endblock content %}

project/apps/cliente/templates/cliente/cliente_list.html
{% extends 'core/base.html' %}

{% block content_title %}
ABM de clientes
{% endblock content_title %}

{% block content %}
<div class="container">
    <div class="mb-4">
        <form method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar cliente">
        </form>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Alta</th>
            </tr>
        </thead>
        <tbody>

            <a href="{% url 'cliente:cliente_form' %}" class="btn btn-danger">Nuevo cliente</a>

            {% for comprador in object_list %}
            <tr>
                <td>{{ comprador.nombre }}</td>
                <td>{{ comprador.apellido }}</td>
                <td>{{ comprador.fecha_alta }}</td>
                <td>
                    <a href="{% url 'cliente:cliente_detail' comprador.id %}" class="btn btn-danger">
                        <i class="fas fa-star"></i> Detalle</a>
                    <a href=" {% url 'cliente:cliente_update' comprador.id %}" class="btn btn-danger"><i
                            class="fas fa-pencil-alt"></i> Editar</a>
                    {% if user.is_staff %}
                    <a href="{% url 'cliente:cliente_confirm_delete' comprador.id %}" class="btn btn-danger "><i
                            class="fas fa-trash-alt"></i>Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td class="text-center">La búsqueda no ha arrojado valor.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}