project/apps/catalogo/urls.py
from django.urls import path
from .views import *

app_name = "catalogo"

urlpatterns = [
    path("", index, name="index"),
    path("categoria/list/", CategoriaList.as_view(), name="categoria_list"),
    path("categoria/form/", CategoriaCreate.as_view(), name="categoria_form"),
    path("categoria/update/<int:pk>/",
         CategoriaUpdate.as_view(), name="categoria_update"),
    path("categoria/delete/<int:pk>/",
         CategoriaDelete.as_view(), name="categoria_delete"),
    path("producto/list/", ProductoList.as_view(), name="producto_list"),
    path("producto/form/", ProductoCreate.as_view(), name="producto_form"),
    path("producto/update/<int:pk>/",
         ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>/", ProductoDelete.as_view(),
         name="producto_confirm_delete"),
    path("producto/detail/<int:pk>/",
         ProductoDetail.as_view(), name="producto_detail"),
    path("venta/list/", VentaList.as_view(), name="venta_list"),
    path("venta/form/", VentaCreate.as_view(), name="venta_form"),
    path("venta/update/<int:pk>/", VentaUpdate.as_view(), name="venta_update"),
    path("venta/delete/<int:pk>/", VentaDelete.as_view(),
         name="venta_confirm_delete"),
]

project/apps/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact_view, name="contact_form"),
    path("contacto_exitoso/", contacto_exitoso, name="contacto_exitoso"),
    path("about/", about, name="about"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("catalogo/", include("catalogo.urls")),

]

project/apps/core/models.py
from django.db import models

# Create your models here.

class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    mensaje = models.TextField()
    fecha_envio = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

project/apps/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Contacto

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre', 'email', 'mensaje']
        
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
    }

project/apps/core/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from .forms import *


def index(request):
    return render(request, "core/index.html")


def contact(request):
    return render(request, "core/contact_form.html")


def about(request: HttpRequest) -> HttpResponse:
    return render(request, "core/about.html")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'core/register.html', {"form": form})


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:contacto_exitoso')
    else:
        form = ContactForm()
    return render(request, 'core/contact_form.html', {'form': form})


def contacto_exitoso(request):
    return render(request, "core/contacto_exitoso.html")

project/apps/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}

<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="text-center">
        <h1 class="display-4">Bienvenid@ a Bazar Deco</h1>
        <p class="lead">Mi nombre es Karina Dalton, soy Contadora Pública especializada en la industria Fintech. De ahí
            mi primer contacto con el mundo de la programación y la tecnología. Mi deseo es poder poder fusionar ambos
            conocimientos y poder buscar soluciones a los problemas que hay mi rubro. Este es mi link a mi perfil de
            LinkedIn.</p>

        <a href="https://www.linkedin.com/in/karina-gabriela-dalton/" target="_blank">Karina Dalton</a>
    </div>
</div>

{% endblock content %}

project/apps/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>BAZAR DECO</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <style>
        body {
            margin-bottom: 70px;
        }
    </style>

    {% include 'core/navbar.html' %}

    <!-- Page Content-->
    <div class="container px-4 px-lg-5; overflow-y: auto;">
        <!-- Heading Row-->
        <div class="row gx-4 gx-lg-5 align-items-center my-3">
            <h1 class="font-weight-light">
                {% block content_title %}
                {% endblock content_title %}
            </h1>

        </div>

        {% block content %}

        {% endblock content %}

    </div>


    {% include 'core/footer.html' %}

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'core/js/scripts.js' %}"></script>
</body>

</html>

project/apps/core/templates/core/contact_form.html
{% extends 'core/base.html' %}

{% block content_title %}
Envianos tu consulta o comentario
{% endblock content_title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>

</form>
{% endblock content %}

project/apps/core/templates/core/contacto_exitoso.html
{% extends 'core/base.html' %}


{% block content %}

<body>
    <h1>¡Gracias por contactarnos!</h1>
    <p>Tu mensaje ha sido enviado con éxito.</p>


</body>

</html>
{% endblock content %}

project/apps/core/templates/core/footer.html
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Copyright &copy; Karina Dalton 2024</p>
    </div>
</footer>

project/apps/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content_title %}

{% endblock content_title %}

{% block content %}

<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/portada_deco.jpg' %}"
            alt="..." style="width: 100%; max-width: 400px" /></div>
    <div class="col-lg-5">
        <h1 class="font-weight-light text-center" style="max-width: 100%"><i>Bienvenidos a</i></h1>
        <h1 class="font-weight-light text-center" style="max-width: 100%"><i>BAZAR DECO</i></h1>
        <p class=" text-center">Arma el hogar de tus sueños</p>
        <a class="btn btn-danger btn-lg px-4 me-sm-3 d-flex justify-content-center"
            href="{% url 'catalogo:index' %}">Entrar</a>
    </div>
</div>


{% endblock content %}

project/apps/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Login
{% endblock title %}

{% block content_title %}
Login
{% endblock content_title %}


{% block content %}

<form method="post" class="form-control">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="hidden" name="next" value="{% url 'catalogo:index' %}">



    <button type="submit" class="btn btn-danger">Iniciar sesión</button>
    <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>


</form>
{% endblock content %}

project/apps/core/templates/core/logout.html
{% extends 'core/base.html' %}


{% block content %}

<body>
    <h2>Se ha cerrado tu sesion</h2>
    <p>Hasta la próxima!!!</p>


</body>

</html>
{% endblock content %}

project/apps/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
                <a href="{% url 'core:index' %}" class="navbar-brand" type="button">Bazar Deco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"><span
                                class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                <li class="nav-item"><a class="nav-link {% if request.path == '/' %} active {% endif %}"
                                                href="{% url 'core:index' %}">Inicio</a></li>
                                <li class="nav-item"><a
                                                class="nav-link {% if '/catalogo/' in request.path %} active {% endif %}"
                                                href="{% url 'catalogo:index' %}">Menu</a></li>
                                <li class="nav-item"><a
                                                class="nav-link {% if '/about/' in request.path %} active {% endif %}"
                                                href="{% url 'core:about' %}">Nosotros</a></li>
                                <li class="nav-item"><a
                                                class="nav-link {% if '/contact/form/' in request.path %} active {% endif %}"
                                                href="{% url 'core:contact_form' %}">Contacto</a></li>
                                {% if user.is_staff %}
                                <li class="nav-item"><a
                                                class="nav-link {% if '/admin/' in request.path %} active {% endif %}"
                                                href="{% url 'admin:index' %}">Administración</a></li>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <li class="nav-item nav-link text-bg-secondary">{{ user.username }}</li>
                                <li class="nav-item">
                                        <form action="{% url 'core:logout' %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-dark">Logout</button>
                                        </form>
                                </li>
                                {% else %}
                                <li class="nav-item"><a
                                                class="nav-link {% if '/register/' in request.path %} active {% endif %}"
                                                href="{% url 'core:register' %}">Registrarse</a></li>
                                <li class="nav-item"><a
                                                class="nav-link {% if '/login/' in request.path %} active {% endif %}"
                                                href="{% url 'core:login' %}">Login</a></li>
                                {% endif %}
                        </ul>
                </div>
        </div>
</nav>

project/apps/core/templates/core/register.html
{% extends 'core/base.html' %}



{% block content_title %}
Registro de usuario
{% endblock content_title %}

{% block content %}

<form method="post" class="form-control">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Registrar Usuario</button>
    <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>


</form>
{% endblock content %}